const chenachuaNames = {
  traditional: [
    "Dju'Rik",
    "Dju'Rik-lek",
    "Dju'uvi",
    "Hek",
    "Hek'Dju-ivi",
    "Hek'Hek",
    "Ivi-Xia'hek",
    "Ivi'tspek",
    "Ivi'ile",
    "Pitx-Pitx",
    "Prit'skep'iki-pak",
    "Rik-Rik",
    "Tik'Dju",
    "Tik'Dju-Xiat'spek",
    "Tik'rati",
    "Tik'Tik",
    "Tu'iki",
    "Tu'ke-hek",
    "Tu'Laki-um",
    "Tu'Tu",
    "Tu'um",
    "Vilk-Rik-Pa-Dju",
    "Xia'tspek",
    "Xiat-Pitx",
    "Xiat'Rak",
    "Xiatl",
    "Ze'vivi-Dju",
    "Zev-Hek",
    "Zev-Ivi",
  ],
} as const;

export { chenachuaNames };
