import { GenderedNamesObj } from "./names-types";

const torlishNames: GenderedNamesObj = {
  feminine: [
    "Borduvia",
    "Cerathey",
    "Cheyle",
    "Etya",
    "Ialda",
    "Iniknek",
    "Lurencya",
    "Maedyr",
    "Mepalti",
    "Mepatell",
    "Minnelek",
    "Nalenthey",
    "Nalvara",
    "Pradh'malis",
    "Vhaeb",
    "Vhaedan",
    "Vhaelafra",
    "Vhaelechey",
    "Vhaelercya",
    "Vhaelycy",
    "Vhaennilar",
    "Vhaerana",
    "Vhaessek",
    "Zhelcya",
    "Zhella",
  ],
  masculine: [
    "Athalis",
    "Athanracys",
    "Bolantar",
    "Hestus",
    "Jelekancys",
    "Jogatus",
    "Kalytar",
    "Marmillan",
    "Marolis",
    "Mas'dmas",
    "Masdanikdars",
    "Mialdo",
    "Mormandan",
    "Parkhunavas",
    "Pelmatus",
    "Praelbins",
    "Raeln",
    "Raeloric",
    "Rahaelytar",
    "Then'tier",
    "Upal",
    "Uskecys",
    "Vhesantias",
    "Vhlen'bors",
    "Vhor",
  ],
} as const;

export { torlishNames };
